# Generated by Django 3.2 on 2021-06-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blurb',
            field=models.TextField(default="Let's grab a kayak and cross the Atlantic"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(default='https://www.linkedin.com/in/pabloguarneros/'),
            preserve_default=False,
        ),
    ]
