# Generated by Django 3.2 on 2021-07-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210617_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='linkedin',
            new_name='patreon',
        ),
    ]
