# Generated by Django 3.2 on 2021-07-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_linkedin_user_patreon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='explorable',
            field=models.BooleanField(default=False),
        ),
    ]
