# Generated by Django 3.2 on 2021-06-17 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_sectionnode_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionnode',
            name='images',
        ),
        migrations.AddField(
            model_name='nodeimages',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.sectionnode'),
            preserve_default=False,
        ),
    ]
