# Generated by Django 3.2 on 2021-06-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_sectionnode_squishy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionnode',
            name='z_position',
            field=models.IntegerField(default=-200),
        ),
    ]
