# Generated by Django 3.2 on 2021-06-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_sectionnode_z_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionnode',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sectionnode',
            name='title',
            field=models.CharField(default='My New Node', max_length=60),
        ),
    ]
