# Generated by Django 3.2 on 2021-06-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20210618_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionnode',
            name='title',
            field=models.CharField(default='My New Node', max_length=60, null=True),
        ),
    ]
