# Generated by Django 3.2 on 2021-06-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_alter_sectionnode_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
