# Generated by Django 3.2 on 2021-06-30 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_alter_lesson_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeimages',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='rooms.sectionnode'),
        ),
    ]
