# Generated by Django 3.2 on 2021-06-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0021_auto_20210630_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeimages',
            name='category',
            field=models.IntegerField(choices=[(0, 'Sticker'), (1, 'Photo'), (2, 'Illustration'), (3, 'Graph')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='nodeimages',
            name='title',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
