# Generated by Django 3.2 on 2021-07-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0023_nodeimages_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='nodeimages',
            name='tags',
            field=models.ManyToManyField(related_name='image_tag', to='rooms.ImageTag'),
        ),
    ]
