# Generated by Django 3.2 on 2021-07-01 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0025_imagetag_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeimages',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_owner', to='rooms.sectionnode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='citation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='nodeimages',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='image_tag', to='rooms.ImageTag'),
        ),
    ]
