# Generated by Django 3.2 on 2021-07-01 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0026_auto_20210701_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeimages',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_owner', to='rooms.lesson'),
        ),
    ]
