# Generated by Django 3.2 on 2021-07-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0028_alter_nodeimages_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionnode',
            name='color',
            field=models.CharField(default='F5BD1F', max_length=8),
        ),
        migrations.AlterField(
            model_name='sectionnode',
            name='squishy',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sectionnode',
            name='x_position',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sectionnode',
            name='y_position',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sectionnode',
            name='z_position',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=7),
        ),
    ]
