# Generated by Django 3.2 on 2021-07-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0029_auto_20210703_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionnode',
            name='y_position',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
