# Generated by Django 3.2 on 2021-08-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0032_rename_ispublic_lesson_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodeimages',
            options={'ordering': ['image']},
        ),
    ]
