# Generated by Django 3.2 on 2021-08-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0033_alter_nodeimages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='nodes',
            field=models.ManyToManyField(blank=True, related_name='lesson_for_nodes', to='rooms.SectionNode'),
        ),
    ]
