# Generated by Django 3.2 on 2021-08-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0034_alter_lesson_nodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='controls',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='template',
        ),
    ]
