# Generated by Django 3.2 on 2021-08-11 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0035_auto_20210811_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.AlterField(
            model_name='nodeimages',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_owner', to='rooms.lesson'),
        ),
    ]
