# Generated by Django 3.2 on 2021-08-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0036_auto_20210811_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionnode',
            name='quat_w',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
        ),
        migrations.AddField(
            model_name='sectionnode',
            name='quat_x',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='sectionnode',
            name='quat_y',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='sectionnode',
            name='quat_z',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='sectionnode',
            name='scale',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
