# Generated by Django 3.2 on 2021-08-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0037_auto_20210811_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionnode',
            name='scale',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=6),
        ),
    ]
