# Generated by Django 3.2 on 2021-08-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0038_alter_sectionnode_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionnode',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sectionnode',
            name='squishy',
        ),
        migrations.AlterField(
            model_name='sectionnode',
            name='quat_w',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sectionnode',
            name='quat_x',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sectionnode',
            name='quat_y',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sectionnode',
            name='quat_z',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sectionnode',
            name='scale',
            field=models.DecimalField(decimal_places=4, default=0.5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sectionnode',
            name='x_position',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sectionnode',
            name='y_position',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sectionnode',
            name='z_position',
            field=models.DecimalField(decimal_places=4, default=-1, max_digits=7),
        ),
    ]
