# Generated by Django 3.2 on 2021-10-13 17:30

from django.db import migrations, models
import minervaremote.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('link', models.URLField(max_length=320)),
                ('photo', models.ImageField(upload_to=minervaremote.models.memory_image_directory_path)),
            ],
        ),
    ]
