# Generated by Django 3.2 on 2021-10-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minervaremote', '0002_memory_memory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='link',
            field=models.URLField(max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
