# Generated by Django 3.2 on 2021-10-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minervaremote', '0003_auto_20211023_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='link',
            field=models.URLField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
