# Generated by Django 3.2 on 2021-11-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minervaremote', '0004_auto_20211023_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='memory_category',
            field=models.IntegerField(choices=[(1, 'Farming'), (2, 'Pet'), (3, 'Art')], default=1, null=True),
        ),
    ]
