# Generated by Django 3.2 on 2021-11-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minervaremote', '0005_alter_memory_memory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
